export const menu = [
  { id: "bom-1", name: "Pumpkin Spice Bagel", ingredients: [], price: 0 },
  {
    id: "ccom-1",
    name: "Chocolate Cream Cheese",
    ingredients: [],
    price: 0,
  },
  {
    id: "si-1",
    name: "Classic Egg & Cheese",
    ingredients: ["Egg", "Cheddar Cheese", "Toasted Bun", "Butter"],
    price: 4.99,
  },
  {
    id: "si-2",
    name: "Bacon Avocado Dfeluxe",
    ingredients: [
      "Egg",
      "Bacon",
      "Avocado",
      "Cheddar Cheese",
      "Toasted Bun",
      "Chipotle Mayo",
    ],
    price: 6.99,
  },
  {
    id: "si-3",
    name: "Veggie Sunrise",
    ingredients: [
      "Egg",
      "Tomato",
      "Spinach",
      "Mushrooms",
      "Swiss Cheese",
      "Whole Wheat Bun",
    ],
    price: 5.99,
  },
  {
    id: "si-4",
    name: "The Lumberjack",
    ingredients: [
      "Egg",
      "Bacon",
      "Sausage",
      "Ham",
      "Cheddar Cheese",
      "Toasted Bun",
      "Maple Butter",
    ],
    price: 7.99,
  },
  { id: "bagel-1", name: "French Toast", ingredients: [], price: 1.5 },
  { id: "bagel-2", name: "Sun-dried Tomato", ingredients: [], price: 1.5 },
  { id: "bagel-3", name: "Jalapeno", ingredients: [], price: 1.5 },
  {
    id: "bagel-4",
    name: "Whole Wheat Everything",
    ingredients: [],
    price: 1.5,
  },
  { id: "bagel-5", name: "Plain", ingredients: [], price: 1.5 },
  { id: "bagel-6", name: "Everything", ingredients: [], price: 1.5 },
  { id: "bagel-7", name: "Sesame", ingredients: [], price: 1.5 },
  { id: "bagel-8", name: "Cinnamon Raisin", ingredients: [], price: 1.5 },
  { id: "bagel-9", name: "Asiago Cheese", ingredients: [], price: 1.5 },
  { id: "bagel-10", name: "Blueberry", ingredients: [], price: 1.5 },
  { id: "bagel-11", name: "Garlic", ingredients: [], price: 1.5 },
  { id: "bagel-12", name: "Whole Wheat", ingredients: [], price: 1.5 },
  { id: "bagel-13", name: "Pumpkin Spice", ingredients: [], price: 1.5 },
  { id: "cc-1", name: "Plain", ingredients: [], price: 0 },
  { id: "cc-2", name: "Scallion", ingredients: [], price: 0 },
  { id: "cc-3", name: "Veggie", ingredients: [], price: 0 },
  { id: "cc-4", name: "Honey Walnut", ingredients: [], price: 0 },
  { id: "cc-5", name: "Strawberry", ingredients: [], price: 0 },
  { id: "cc-6", name: "Lox Spread", ingredients: [], price: 0 },
  { id: "cc-7", name: "Butter", ingredients: [], price: 0 },
  { id: "cc-8", name: "Peanut Butter", ingredients: [], price: 0 },
  { id: "cc-9", name: "Hummus", ingredients: [], price: 0 },
  { id: "cc-10", name: "Avocado Spread", ingredients: [], price: 0 },
  {
    id: "salad-1",
    name: "Garden Salad",
    ingredients: [
      "Romaine Lettuce",
      "Cherry Tomatoes",
      "Cucumber",
      "Carrots",
      "Red Onion",
      "Ranch Dressing",
    ],
    price: 6.99,
  },
  {
    id: "salad-2",
    name: "Caesar Salad",
    ingredients: [
      "Romaine Lettuce",
      "Parmesan Cheese",
      "Croutons",
      "Caesar Dressing",
    ],
    price: 7.99,
  },
  {
    id: "salad-3",
    name: "Greek Salad",
    ingredients: [
      "Romaine Lettuce",
      "Feta Cheese",
      "Kalamata Olives",
      "Cherry Tomatoes",
      "Cucumber",
      "Red Onion",
      "Greek Dressing",
    ],
    price: 8.49,
  },
  {
    id: "salad-4",
    name: "Cobb Salad",
    ingredients: [
      "Romaine Lettuce",
      "Grilled Chicken",
      "Bacon",
      "Hard-Boiled Egg",
      "Avocado",
      "Cherry Tomatoes",
      "Blue Cheese",
      "Ranch Dressing",
    ],
    price: 9.99,
  },
  {
    id: "salad-5",
    name: "Spinach & Berry Salad",
    ingredients: [
      "Baby Spinach",
      "Strawberries",
      "Blueberries",
      "Goat Cheese",
      "Candied Pecans",
      "Balsamic Vinaigrette",
    ],
    price: 8.99,
  },
  {
    id: "salad-6",
    name: "Southwest Salad",
    ingredients: [
      "Romaine Lettuce",
      "Grilled Chicken",
      "Black Beans",
      "Corn",
      "Cherry Tomatoes",
      "Avocado",
      "Tortilla Strips",
      "Chipotle Ranch Dressing",
    ],
    price: 9.49,
  },
  {
    id: "sandwiches-bf-1",
    name: "Classic Egg & Cheese",
    ingredients: ["Egg", "Cheddar Cheese", "Toasted Bun", "Butter"],
    price: 4.99,
  },
  {
    id: "sandwiches-bf-2",
    name: "Bacon Egg & Cheese",
    ingredients: ["Egg", "Bacon", "Cheddar Cheese", "Toasted Bun", "Butter"],
    price: 5.49,
  },
  {
    id: "sandwiches-bf-3",
    name: "Sausage Egg & Cheese",
    ingredients: ["Egg", "Sausage", "Cheddar Cheese", "Toasted Bun", "Butter"],
    price: 5.49,
  },
  {
    id: "sandwiches-bf-4",
    name: "Ham Egg & Cheese",
    ingredients: ["Egg", "Ham", "Cheddar Cheese", "Toasted Bun", "Butter"],
    price: 5.49,
  },
  {
    id: "sandwiches-bf-5",
    name: "Bacon Avocado Deluxe",
    ingredients: [
      "Egg",
      "Bacon",
      "Avocado",
      "Cheddar Cheese",
      "Toasted Bun",
      "Chipotle Mayo",
    ],
    price: 6.99,
  },
  {
    id: "sandwiches-bf-6",
    name: "Veggie Sunrise",
    ingredients: [
      "Egg",
      "Tomato",
      "Spinach",
      "Mushrooms",
      "Swiss Cheese",
      "Whole Wheat Bun",
    ],
    price: 5.99,
  },
  {
    id: "sandwiches-bf-7",
    name: "The Lumberjack",
    ingredients: [
      "Egg",
      "Bacon",
      "Sausage",
      "Ham",
      "Cheddar Cheese",
      "Toasted Bun",
      "Maple Butter",
    ],
    price: 7.99,
  },
  {
    id: "sandwiches-bf-8",
    name: "Smoked Salmon",
    ingredients: [
      "Egg",
      "Smoked Salmon",
      "Cream Cheese",
      "Red Onion",
      "Toasted Bagel",
    ],
    price: 8.49,
  },
  {
    id: "sandwiches-l-1",
    name: "Turkey Club",
    ingredients: [
      "Turkey",
      "Bacon",
      "Lettuce",
      "Tomato",
      "Mayonnaise",
      "Toasted Bread",
    ],
    price: 7.99,
  },
  {
    id: "sandwiches-l-2",
    name: "BLT",
    ingredients: ["Bacon", "Lettuce", "Tomato", "Mayonnaise", "Toasted Bread"],
    price: 6.49,
  },
  {
    id: "sandwiches-l-3",
    name: "Chicken Salad",
    ingredients: ["Chicken Salad", "Lettuce", "Tomato", "Toasted Bread"],
    price: 6.99,
  },
  {
    id: "sandwiches-l-4",
    name: "Tuna Melt",
    ingredients: ["Tuna Salad", "Cheddar Cheese", "Toasted Bread", "Pickles"],
    price: 7.49,
  },
  {
    id: "sandwiches-l-5",
    name: "Veggie Delight",
    ingredients: [
      "Avocado",
      "Cucumber",
      "Tomato",
      "Lettuce",
      "Swiss Cheese",
      "Hummus",
      "Whole Wheat Bread",
    ],
    price: 6.99,
  },
  {
    id: "sandwiches-l-6",
    name: "Reuben",
    ingredients: [
      "Corned Beef",
      "Swiss Cheese",
      "Sauerkraut",
      "Russian Dressing",
      "Rye Bread",
    ],
    price: 8.49,
  },

  // Specialty Sandwiches
  {
    id: "sandwiches-s-1",
    name: "Brookhaven",
    ingredients: [
      "Grilled Chicken",
      "Bacon",
      "Avocado",
      "Swiss Cheese",
      "Lettuce",
      "Tomato",
      "Honey Mustard",
      "Toasted Bread",
    ],
    price: 8.99,
  },
  {
    id: "sandwiches-s-2",
    name: "Twin Towers",
    ingredients: [
      "Turkey",
      "Roast Beef",
      "Lettuce",
      "Tomato",
      "Cheddar Cheese",
      "Mayo",
      "Toasted Bread",
    ],
    price: 9.49,
  },
  {
    id: "sandwiches-s-3",
    name: "R&B Combo",
    ingredients: [
      "Roast Beef",
      "Bacon",
      "Lettuce",
      "Tomato",
      "Cheddar Cheese",
      "Mustard",
      "Toasted Bread",
    ],
    price: 8.99,
  },
  {
    id: "sandwiches-s-4",
    name: "B.U. Special",
    ingredients: [
      "Grilled Chicken",
      "Avocado",
      "Bacon",
      "Swiss Cheese",
      "Lettuce",
      "Tomato",
      "Ranch Dressing",
      "Toasted Bread",
    ],
    price: 9.49,
  },

  // Pastrami Sandwiches
  {
    id: "sandwiches-p-1",
    name: "Chicken Salad",
    ingredients: ["Chicken Salad", "Lettuce", "Tomato", "Toasted Bread"],
    price: 6.99,
  },
  {
    id: "sandwiches-p-2",
    name: "Pastrami Reuben",
    ingredients: [
      "Pastrami",
      "Swiss Cheese",
      "Sauerkraut",
      "Russian Dressing",
      "Rye Bread",
    ],
    price: 8.99,
  },
  {
    id: "sandwiches-p-3",
    name: "Cheese Steak",
    ingredients: [
      "Steak",
      "Peppers",
      "Onions",
      "Cheese",
      "Toasted Hoagie Roll",
    ],
    price: 9.49,
  },
  {
    id: "sandwiches-p-4",
    name: "Turkey Club",
    ingredients: [
      "Turkey",
      "Bacon",
      "Lettuce",
      "Tomato",
      "Mayonnaise",
      "Toasted Bread",
    ],
    price: 7.99,
  },
  {
    id: "sandwiches-p-5",
    name: "Whitefish Salad",
    ingredients: ["Whitefish Salad", "Lettuce", "Tomato", "Toasted Bread"],
    price: 7.49,
  },
  {
    id: "sandwiches-p-6",
    name: "Italian",
    ingredients: [
      "Salami",
      "Pepperoni",
      "Provolone Cheese",
      "Lettuce",
      "Tomato",
      "Olives",
      "Italian Dressing",
      "Hoagie Roll",
    ],
    price: 8.49,
  },
  {
    id: "sandwiches-p-7",
    name: "The Bomb",
    ingredients: [
      "Grilled Chicken",
      "Bacon",
      "Avocado",
      "Swiss Cheese",
      "Lettuce",
      "Tomato",
      "Chipotle Mayo",
      "Toasted Roll",
    ],
    price: 9.99,
  },
  {
    id: "panini-1",
    name: "Caprese Panini",
    ingredients: [
      "Mozzarella",
      "Tomato",
      "Basil",
      "Balsamic Glaze",
      "Ciabatta Bread",
    ],
    price: 7.99,
  },
  {
    id: "panini-2",
    name: "Turkey Pesto",
    ingredients: [
      "Turkey",
      "Pesto Sauce",
      "Mozzarella Cheese",
      "Tomato",
      "Ciabatta Bread",
    ],
    price: 8.49,
  },
  {
    id: "panini-3",
    name: "Cuban",
    ingredients: [
      "Roast Pork",
      "Ham",
      "Swiss Cheese",
      "Pickles",
      "Mustard",
      "Ciabatta Bread",
    ],
    price: 8.99,
  },
  {
    id: "panini-4",
    name: "Chicken Bacon Ranch",
    ingredients: [
      "Grilled Chicken",
      "Bacon",
      "Ranch Dressing",
      "Cheddar Cheese",
      "Tomato",
      "Ciabatta Bread",
    ],
    price: 8.99,
  },
  {
    id: "panini-5",
    name: "Mediterranean Veggie",
    ingredients: [
      "Hummus",
      "Cucumber",
      "Tomato",
      "Olives",
      "Feta Cheese",
      "Spinach",
      "Whole Wheat Bread",
    ],
    price: 7.49,
  },
  {
    id: "panini-6",
    name: "Tuna Melt Panini",
    ingredients: ["Tuna Salad", "Cheddar Cheese", "Pickles", "Toasted Bread"],
    price: 8.49,
  },
  {
    id: "panini-7",
    name: "Italian",
    ingredients: [
      "Salami",
      "Pepperoni",
      "Provolone Cheese",
      "Olives",
      "Tomato",
      "Lettuce",
      "Italian Dressing",
      "Ciabatta Bread",
    ],
    price: 8.49,
  },
  {
    id: "panini-8",
    name: "Apple Brie",
    ingredients: [
      "Apple Slices",
      "Brie Cheese",
      "Honey",
      "Arugula",
      "Ciabatta Bread",
    ],
    price: 8.99,
  },

  // Omelets
  {
    id: "omelet-1",
    name: "Classic Cheese",
    ingredients: ["Eggs", "Cheddar Cheese", "Swiss Cheese", "Salt", "Pepper"],
    price: 6.99,
  },
  {
    id: "omelet-2",
    name: "Western",
    ingredients: ["Eggs", "Ham", "Bell Peppers", "Onions", "Cheddar Cheese"],
    price: 7.99,
  },
  {
    id: "omelet-3",
    name: "Veggie Delight",
    ingredients: [
      "Eggs",
      "Spinach",
      "Mushrooms",
      "Tomato",
      "Onions",
      "Bell Peppers",
      "Feta Cheese",
    ],
    price: 7.49,
  },
  {
    id: "omelet-4",
    name: "Meat Lover's",
    ingredients: ["Eggs", "Bacon", "Sausage", "Ham", "Cheddar Cheese"],
    price: 8.49,
  },
  {
    id: "omelet-5",
    name: "Greek",
    ingredients: ["Eggs", "Feta Cheese", "Spinach", "Tomato", "Olives"],
    price: 7.99,
  },
  {
    id: "omelet-6",
    name: "Smoked Salmon",
    ingredients: ["Eggs", "Smoked Salmon", "Cream Cheese", "Capers", "Dill"],
    price: 8.99,
  },
  {
    id: "omelet-7",
    name: "Southwest",
    ingredients: [
      "Eggs",
      "Avocado",
      "Salsa",
      "Cheddar Cheese",
      "Jalapeños",
      "Cilantro",
    ],
    price: 8.49,
  },
  {
    id: "omelet-8",
    name: "Farmer's Market",
    ingredients: [
      "Eggs",
      "Tomato",
      "Onions",
      "Bell Peppers",
      "Spinach",
      "Goat Cheese",
    ],
    price: 7.99,
  },
  { id: "side-1", name: "Hash Browns", ingredients: [], price: 0 },
  { id: "side-2", name: "Breakfast Potatoes", ingredients: [], price: 0 },
  { id: "side-3", name: "Fresh Fruit Cup", ingredients: [], price: 0 },
  { id: "side-4", name: "Yogurt Parfait", ingredients: [], price: 0 },
  { id: "side-5", name: "Side Salad", ingredients: [], price: 0 },
  { id: "side-6", name: "Kettle Chips", ingredients: [], price: 0 },
  { id: "side-7", name: "Bacon (3 slices)", ingredients: [], price: 0 },
  { id: "side-8", name: "Sausage Links (2)", ingredients: [], price: 0 },
  { id: "side-9", name: "Extra Egg", ingredients: [], price: 0 },
  { id: "toppings-1", name: "Lettuce", ingredients: [], price: 0 },
  { id: "toppings-2", name: "Tomato", ingredients: [], price: 0 },
  { id: "toppings-3", name: "Green peppers", ingredients: [], price: 0 },
  { id: "toppings-4", name: "Banana peppers", ingredients: [], price: 0 },
  { id: "toppings-5", name: "Sweet peppers", ingredients: [], price: 0 },
  { id: "toppings-6", name: "Onion", ingredients: [], price: 0 },
  { id: "toppings-7", name: "Black olives", ingredients: [], price: 0 },
  { id: "toppings-8", name: "Pickles", ingredients: [], price: 0 },
  { id: "toppings-9", name: "Mayonnaise", ingredients: [], price: 0 },
  { id: "toppings-10", name: "Sub sauce", ingredients: [], price: 0 },
  { id: "toppings-11", name: "Yellow mustard", ingredients: [], price: 0 },
  { id: "toppings-12", name: "Spicy mustard", ingredients: [], price: 0 },
  { id: "toppings-13", name: "Honey mustard", ingredients: [], price: 0 },
  { id: "toppings-14", name: "Thousand island", ingredients: [], price: 0 },
  { id: "toppings-15", name: "American cheese", ingredients: [], price: 0 },
  { id: "toppings-16", name: "Swiss cheese", ingredients: [], price: 0 },
  { id: "toppings-17", name: "Provolone cheese", ingredients: [], price: 0 },
  { id: "dessert-1", name: "Chocolate Chip Cookie", ingredients: [], price: 0 },
  { id: "dessert-2", name: "Blueberry Muffin", ingredients: [], price: 0 },
  { id: "dessert-3", name: "Croissant", ingredients: [], price: 0 },
  { id: "dessert-4", name: "Cinnamon Roll", ingredients: [], price: 0 },
  { id: "dessert-5", name: "Brownie", ingredients: [], price: 0 },
  { id: "dessert-6", name: "Cheesecake Slice", ingredients: [], price: 0 },
  { id: "dessert-7", name: "Danish", ingredients: [], price: 0 },
  { id: "dessert-8", name: "Scone", ingredients: [], price: 0 },
  { id: "dessert-9", name: "Pumpkin Bread", ingredients: [], price: 0 },
];
